POST http://localhost:4000/users
Content-Type: application/json

{
  "username":"1artart.81mile",
  "password":"art123456",
  "name":"chaiyaphat",
  "surname":"supharak"
}

###
GET http://localhost:4000/users
Content-Type: application/json


###
GET http://localhost:4000/users/60b2918b75399124f01464dc
Content-Type: application/json

###
PATCH  http://localhost:4000/users
Content-Type: application/json

{
  "userId":"60b29083862e983dcc02e4b3",
  "username":"newnew.81mile",
  "password":"art123456",
  "name":"new12",
  "surname":"new2020"
}

###
DELETE  http://localhost:4000/users
Content-Type: application/json

{
  "userId":"60b2918b75399124f01464dc"
}